# -*- coding: utf-8 -*-
"""TrashAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_EtD7sN1FcvXopaDgLp5pywY1zaUI31
"""

!nvidia-smi

!pip3 install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()
!yolo checks

!pip3 install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="NTMKLTr6NfuCeFwkvGDz")
project = rf.workspace("nora-slimani").project("trash-detection-otdmj")
version = project.version(35)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=40 imgsz=640